### ISSUE TITLE
Handling VSCP_TYPE_PROTOCOL_READ_WRITE_RESPONSE

### ISSUE THREAD

**Issue by troky** [BlueAndi/vscp-framework#10]
Is it possible to create callback (callout) for `VSCP_TYPE_PROTOCOL_READ_WRITE_RESPONSE `and `VSCP_TYPE_PROTOCOL_PAGE_READ_WRITE_RESPONSE `?

... or, for simplicity, route that events through existing `vscp_portable_provideEvent(vscp_RxMessage const * const msg)`

... oooor route all unimplemented (non-bootloader related) protocol events?

**Comment by BlueAndi** [comment]
Can you explain me your use case?
Does your node reads a register from another node?

**Comment by troky** [comment]
There are two scenarios actually:
1. segment controller reads/writes node configuration/serial number, etc..
2. node reads register from segment controller

Register read/write is only reliable mechanism, right? I need to be sure that node received data successfully.

**Comment by BlueAndi** [comment]
Using class1.protocol by the node application may cause problems. Consider that there is no session handling, so if you access a node with e.g. vscpWorks and at the same time the node receives register read/writes from the segment master, it may fail.

Maybe you can explain me the content of the registers and the use case at a more abstract level.

Lets discuss it on a concrete example.
A pushbutton will trigger a lamp on/off. But the pushbutton has a LED, which shall be only on in case the lamp is on and vice versa.
The switch sends a CLASS1.INFORMATION.Button event. If the lamp receives the event and the decision matrix is configured right, it will enable the lamp. After that, the lamp will notify about its status with CLASS1.INFORMATION.On or .Off event.
Now the pushbutton knows for sure, its on or off.

I can just assume that in your case you could also send data via CLASS1.DATA or CLASS1.MEASUREMENT. And the receiving node could confirm it via CLASS1.INFORMATION.Confirm event.

If the problem is that you need 1:1 communication, you could think about using e.g. CLASS1.MEASUREZONE event, which additional contains zone/sub-zone/index information. And because every node can be configured with a dedicated zone/sub-zone, you might use this to retrieve the node specific data.

**Comment by troky** [comment]
I have one main (segment) controller and 1-n NFC card reader nodes with optional BLE module installed.
I need to configure (and/or read configuration) main conroller using mobile phone via NFC (or BLE) connected to any of that nodes. In my case that could be the only way to configure controller because it won't allways be connected to outside world.

In theory I want to make some kind of vscpWorks-like mobile application that talks vscp using NFC/BLE device as communication proxy. That's why I want to use class1.protocol as much as possible.

For simple (i.e. high level) configuration class1.data/class1.measurement with class1.information.confirm is enough.

IMHO, it's up to developer to take care of proper use of class1.protocol and library should enable it :)

**Comment by BlueAndi** [comment]
A general solution with more possibilites will be the following:
![image](https://user-images.githubusercontent.com/9699465/39089075-dd723226-45be-11e8-9679-53303e710d50.png)

Enable VSCP_CONFIG_PROTOCOL_EVENT_NOTIFICATION in the configuration and you will receive all CLASS1.PROTOCOL events in vscp_portable_provideProtocolEvent().

If the application handles a event, it shall return TRUE otherwise FALSE. The core won't handle it in case the application already did it.

**Comment by troky** [comment]
Thanks. I'll test it soon.

**Comment by troky** [comment]
It works. :)

**Comment by BlueAndi** [comment]
Thanks for the feedback! :-)
