### ISSUE TITLE
Missing spec

### ISSUE THREAD

**Issue by troky** [BlueAndi/vscp-framework#21]
How do you keep this library in sync with VSCP specification, i.e. when new event is added?
There are many unimplemented events here as well as complete classes.
Do you have some scripts that auto-generate code or you have to do it by hand?
I would like to help.

**Comment by BlueAndi** [comment]
We are talking about the event modules here: https://github.com/BlueAndi/vscp-framework/tree/master/vscp/events

Years ago the specification was available in PDF (latex) format and as wiki pages. I used in a first approach the wiki pages to generate the sourcecode, avoiding to have to write everything by hand.

This wiki pages were removed later on and unfortunately at this point I didn't generate sourcecode for all classes. Anyway you can image for sure, generating from wiki stuff was not the best solution, but the only possible at this time (didn't know any other source).

Since that I update them manually.

Two or three years ago, I missed a convenient event logger, which receives the events via websocket from the daemon. Additional the idea to generate the event moduls raises up again and I started to define the protocol in XML (see https://github.com/BlueAndi/vscp-framework/blob/master/tools/vscp-protocol/vscp-protocol.xml). This was then the source for the event logger and should be the source for generating the code again. But because lack of time, the progress is slow.

In the meantime Ake had the very good idea (greetings from here :-) ) to keep the classes/types as single source at one place and created https://github.com/grodansparadis/vscp-classes.

Thats were we are right now.

**Comment by troky** [comment]
So, what is your suggestion? 
Let's say I want to add CLASS1.DISPLAY events (vscp_display.c/.h)... Should I do it manually based on existing implementation, should I upgrade vscp-protocol.xml so you can automatically generate .c/.h or should I create some script to import vscp-classes from Ake to your vscp-protocol.xml... oooor create script to create .c/.h from Ake classes directly?

**Comment by BlueAndi** [comment]
To keep single source, would be the best. That would mean to use the .xml and .md files from Ake. But the challenge are the markdown files, because there is no fixed format of them. I guess you need a lot of exception handling in the script.
I still prefer to update the vscp-protocol.xml, which makes it much easier to use it later for generating stuff. But we would have to update it manually, I think and write the corresponding generator. An advantage with the vscp-protocol.xml would be, to be able to add user defined events and generate functions for them.

What would you prefer?

**Comment by troky** [comment]
Well, I prefer updating .xml anyway. I am not sure if creation of some script for automatic import from Ake's markdown+manual correction would take less time than manual import.
I will try to allocate some manpower in next few weeks to work on this matter.
My plan is to create light (open sourced) version of vscpworks for Windows (.NET) so vscp-protocol.xml is way to go.

**Comment by BlueAndi** [comment]
You will find the xml schema for verification here https://github.com/BlueAndi/vscp-framework/tree/master/tools/vscp-protocol-schema
Additional informations are in the vscp-protocol.xml at top as comment.

Why .NET? Is it a must? Ake is working on vscpworksplus, maybe it's possible to share workload.

**Comment by troky** [comment]
.NET Core actually... yes it is a must because all of our software is based on .NET. We don't do anything in wxwidgets nor qt :)

**Comment by BlueAndi** [comment]
Model (vscp-protocol.xml) updated and the VSCP C type headers are generated now.
