### ISSUE TITLE
vscp-core as submodule

### ISSUE THREAD

**Issue by troky** [BlueAndi/vscp-framework#31]
It would be nice to have current vscp/ folder as submodule to vscp-framework. I use several git repos as submodules in my project but I can't (don't want to) do the same with vscp-framework since it has tons of irrelevant files/examples/docs so I have to do manual pull and then copy to keep source tree as clean as possible.
Thoughts?

**Comment by BlueAndi** [comment]
To be honest I thought about it some time ago. The current structure with projects, examples. etc. was just for convenience and simplicity at the same place.

Another idea was to provide the core via platformio too. Unfortunately the arduino part is not so easy to handle, caused by arduino build environment limitations.

I will think about, but please give a little bit time.

**Comment by troky** [comment]
Sure, It was just an idea ;)

**Comment by BlueAndi** [comment]
Waiting for https://github.com/arduino/arduino-cli/pull/502

**Comment by BlueAndi** [comment]
Following platformio library structure. I guess waiting for Arduino to support several include paths, I am retired.
