### ISSUE TITLE
Library is hard to integrate into AVR projects

### ISSUE THREAD

**Issue by onitake** [BlueAndi/vscp-framework#37]
While integrating the AT90 CAN driver into one of my projects, I noticed that linking external libraries to AVR firmware is somewhat problematic. This is particularly true because the vscp-framework makefile uses some unusual compilation flags, which would result in potentially incompatible function call semantics: `-funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums`

If a target program is not built with these parameters, the resulting code would have data type issues, in particular with those functions that use enums (such as `can_set_mode`). Data structures might also end up with a different memory layout.

I ended up not using the shipped makefiles at all, instead compiling all sources together with a central makefile. This has worked very well, after I made sure my custom `config.h` was used everywhere.

I recommend doing away with these compiler parameters. Instead, it's better to use `#pragma pack` or `__attribute__ ((__packed__))` on those data structures that require it. `-funsigned-char` and `-funsigned-bitfields` are unnecessary when exact stdint data types are used. And as for `-fshort-enums` - I wonder if it's not better to just drop the enums and use `uint8_t` and macros instead. These don't offer bounds checking, but are more predictable in terms of generated machine code.

**Comment by BlueAndi** [comment]
Please note, this repository is mainly for the VSCP framework. Currently it contains examples and live projects too, which may change in the future. The plan is to separate the core from the other stuff.

Original the compiler flags in the makefiles are more or less consistent to the standard flags in a AtmelStudio project. But I see your point, of course. Will consider it during restructering, but need a little bit more time, because I am waiting for a important Arduino IDE feature.

**Comment by onitake** [comment]
Thanks for the explanation.
I'm looking forward to it.
